### panic

**当函数发生 panic 时，它会终止运行，在执行完所有的延迟函数后，程序控制返回到该函数的调用方。这种过程会一直持续下去，直到当前协程的所有函数都返回退出，然后程序会打印出 panic 信息，接着打印出堆栈跟踪，最后程序终止。**

### recover

recover 是一个内建函数，用于重新获得 panic 协程的控制。

**只有在延迟函数内部，调用 recover 才有用。在延迟函数内调用 recover，可以取到 panic 的错误信息，并且停止 panic 续发事件，程序运行恢复正常。**

**只有在相同的 Go 协程中调用 recover 才管用。recover 不能恢复一个不同协程的 panic**